version: '3.8'

services:
  mysql_8:
    container_name: mysql_8
    image: docker.io/bitnami/mysql:8.1
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mybatis
      - MYSQL_USER=hunglk
      - MYSQL_PASSWORD=123456

volumes:
  mysql_data:
    driver: local
